# Generated by Django 5.0.6 on 2024-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('events', models.ManyToManyField(blank=True, related_name='external_users', to='events.event')),
            ],
        ),
    ]
